"""nullable false

Revision ID: 892d847df712
Revises: effc607b0530
Create Date: 2020-12-08 07:38:43.803640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892d847df712'
down_revision = 'effc607b0530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Bug', 'who',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Bug', 'who',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
