"""add root_cause table

Revision ID: effc607b0530
Revises: ca178d741a8f
Create Date: 2020-12-08 07:31:14.638678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'effc607b0530'
down_revision = 'ca178d741a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Root_Cause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_tracker_url', sa.String(), nullable=True),
    sa.Column('root_cause_id', sa.Integer(), nullable=False),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['root_cause_id'], ['Root_Cause.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bug_tracker_url')
    )
    op.create_index(op.f('ix_Bug_root_cause_id'), 'Bug', ['root_cause_id'], unique=False)
    op.drop_table('bug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bug_tracker_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('root_cause', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('who', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('when', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bug_pkey')
    )
    op.drop_index(op.f('ix_Bug_root_cause_id'), table_name='Bug')
    op.drop_table('Bug')
    op.drop_table('Root_Cause')
    # ### end Alembic commands ###
